version: "3.8"

services:
  app:
    build: .
    container_name: stripe-payment-app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:randompassword@postgres:5432/stripe_payment_db

    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: stripe-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: stripe_payment_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
